export const peopleData = [
  {
    id: "1",
    fName: "John",
    lName: "Doe",
    DOB: "2000/12/03",
    Gender: "male",
    nationality: "Indian",
    contactNumber: "1234567890",
    email: "john@gmail.com",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/John_Doe%2C_born_John_Nommensen_Duchac.jpg/1200px-John_Doe%2C_born_John_Nommensen_Duchac.jpg",
    isActive: true,
    role: "Product Manager",
    teams: ["Design", "Product", "Marketing"],
  },
  {
    id: "2",
    fName: "Smith",
    lName: "Tom",
    DOB: "2000/12/03",
    Gender: "male",
    nationality: "Indian",
    contactNumber: "1234567890",
    email: "john@gmail.com",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/John_Doe%2C_born_John_Nommensen_Duchac.jpg/1200px-John_Doe%2C_born_John_Nommensen_Duchac.jpg",
    isActive: true,
    role: "Product Manager",
    teams: ["Design", "Product", "Marketing", "Fullstack Developer"],
  },
  {
    id: "3",
    fName: "Emily",
    lName: "Clark",
    DOB: "1995/07/20",
    Gender: "female",
    nationality: "American",
    contactNumber: "9876543210",
    email: "emily.clark@example.com",
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    isActive: true,
    role: "Software Engineer",
    teams: ["Development",   "QA"],
  },
  {
    id: "4",
    fName: "Michael",
    lName: "Brown",
    DOB: "1988/04/15",
    Gender: "male",
    nationality: "British",
    contactNumber: "4567891230",
    email: "michael.brown@example.com",
    image: "https://randomuser.me/api/portraits/men/46.jpg",
    isActive: false,
    role: "DevOps Engineer",
    teams: ["Infrastructure", "Support"],
  },
  {
    id: "5",
    fName: "Sophia",
    lName: "Jones",
    DOB: "1992/11/25",
    Gender: "female",
    nationality: "Canadian",
    contactNumber: "1239876543",
    email: "sophia.jones@example.com",
    image: "https://randomuser.me/api/portraits/women/68.jpg",
    isActive: true,
    role: "UI/UX Designer",
    teams: ["Design", "Marketing"],
  },
  {
    id: "6",
    fName: "David",
    lName: "Wilson",
    DOB: "1985/06/10",
    Gender: "male",
    nationality: "Australian",
    contactNumber: "7890123456",
    email: "david.wilson@example.com",
    image: "https://randomuser.me/api/portraits/men/65.jpg",
    isActive: true,
    role: "Project Manager",
    teams: ["Management", "Development"],
  },
  {
    id: "7",
    fName: "Olivia",
    lName: "Davis",
    DOB: "1997/02/28",
    Gender: "female",
    nationality: "New Zealander",
    contactNumber: "6543219870",
    email: "olivia.davis@example.com",
    image: "https://randomuser.me/api/portraits/women/45.jpg",
    isActive: false,
    role: "Content Strategist",
    teams: ["Content", "Marketing"],
  },
  {
    id: "8",
    fName: "Liam",
    lName: "Taylor",
    DOB: "1991/09/17",
    Gender: "male",
    nationality: "Irish",
    contactNumber: "7896541230",
    email: "liam.taylor@example.com",
    image: "https://randomuser.me/api/portraits/men/48.jpg",
    isActive: true,
    role: "Data Scientist",
    teams: ["Data", "AI"],
  },
  {
    id: "9",
    fName: "Ava",
    lName: "Martin",
    DOB: "1994/05/22",
    Gender: "female",
    nationality: "French",
    contactNumber: "3216549870",
    email: "ava.martin@example.com",
    image: "https://randomuser.me/api/portraits/women/72.jpg",
    isActive: true,
    role: "Marketing Specialist",
    teams: ["Marketing", "Sales"],
  },
  {
    id: "10",
    fName: "Noah",
    lName: "Harris",
    DOB: "1989/03/14",
    Gender: "male",
    nationality: "South African",
    contactNumber: "9873216540",
    email: "noah.harris@example.com",
    image: "https://randomuser.me/api/portraits/men/73.jpg",
    isActive: true,
    role: "Fullstack Developer",
    teams: ["Development", "Product"],
  },
];
